config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :notes
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}

  root 'pages#home'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  has_many :notes
  
  def github
    Github.new oauth_token: self.token
  end
  
  def repositories
    self.github.repositories.list
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.token = auth.credentials.token
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    if params[:project]
      @notes = current_user.notes.where(project_name: params[:project])
    else
      @notes = current_user.notes.all
    end
    respond_with(@notes)
  end

  def show
    respond_with(@note)
  end

  def new
    @note = current_user.notes.new
    respond_with(@note)
  end

  def edit
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.save
    respond_with(@note)
  end

  def update
    @note.update(note_params)
    respond_with(@note)
  end

  def destroy
    @note.destroy
    respond_with(@note)
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:text, :user_id, :project_name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_repositories.haml
.well.sidebar-nav
  %h3 Public
  %ul.nav.nav-list
    %li.nav-header Repositories
    - user.repositories.each do |repository|
      - if !repository.private
        %li= link_to repository.name, notes_path(project: repository.name)
  %h3 Private
  %ul.nav.nav-list
    %li.nav-header Repositories
    - user.repositories.each do |repository|
      - if repository.private
        %li= link_to repository.name, notes_path(project: repository.name)

app/views/layouts/application.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "DevNotes"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "DevNotes", root_path, class: "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li= link_to "Feed", "#"
              %li= link_to "Notes", notes_path
            - else
              %li= link_to "Home", root_path
          %ul.nav.navbar-nav.navbar-right
            - if !user_signed_in?
              %li= link_to "Sign In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path
            - else
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          = content_for?(:sidebar) ? yield(:sidebar) : ""
      %footer
        %p &copy; Company 2015

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :project_name
    = f.collection_select :project_name, current_user.repositories, :name, :name
  .git-file-name
  .bitbucket-file-name
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
- content_for(:sidebar) do |s|
  = render "layouts/repositories", user: current_user

.panel.panel-default
  .panel-heading
    %h1 Notes
  .panel-body
    = link_to 'New Note', new_note_path, class: "btn btn-success"
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Note
        %th Project Name
        %th
    %tbody
      - @notes.each do |note|
        %tr
          %td= note.text
          %td= note.project_name
          %td
            = link_to 'Show', note, class: "btn btn-default"
            = link_to 'Edit', edit_note_path(note), class: "btn btn-success"
            = link_to 'Delete', note, class: "btn btn-danger", :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/notes/new.html.haml
- content_for(:sidebar) do |s|
  = render "layouts/repositories", user: current_user

%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @note.text
%p
  %b User:
  = @note.user_id
%p
  %b Project:
  = @note.project_name

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path